theme: jekyll-theme-slate
show_downloads: true
title: endmodule
description: Open Source Verilog Modules
# github:
#   zip_url: https://github.com/SagarDevAchar/TheTXTHider/releases/download/release/The.TXT.Hider.v2022.07.19.zip
#   tar_url: https://github.com/SagarDevAchar/TheTXTHider/archive/refs/tags/release.tar.gz
